(function(){
	"use strict";
	
	var tabs = require("./tabs.js");

	var texts = [
		'Lorem ipsum dolor sit amet, consectetur adipiscing elit.' + ' Nam sit amet vestibulum quam, quis fermentum justo. Proin ultricies ex id lectus iaculis, blandit porttitor nulla vestibulum. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer tincidunt leo non gravida scelerisque. Aliquam neque ipsum, ultricies ac mollis quis, vehicula vitae lorem. Mauris ornare urna a aliquam congue. Donec sed tortor egestas sapien volutpat pulvinar at nec erat. Morbi ut tellus in velit tincidunt tincidunt. Mauris vel sapien mauris.',
		'In auctor mauris et lectus feugiat, ut auctor ante blandit. Integer vulputate ipsum lacus, at cursus odio elementum facilisis. Integer sed leo odio. Donec mollis sit amet leo id mattis. Aenean placerat hendrerit ex at pulvinar. Sed vel metus imperdiet, porttitor diam at, bibendum nisl. Pellentesque accumsan magna ac est consequat, vel hendrerit arcu feugiat. Ut tellus neque, condimentum ut enim eget, convallis varius massa. Duis et lorem eget augue facilisis feugiat sit amet sit amet mauris. Nullam dignissim fringilla dolor ac facilisis.',
		'Ut a nunc non libero tincidunt vehicula. Proin posuere nulla eget nunc vehicula molestie. Maecenas at arcu et tellus viverra aliquam at ullamcorper elit. Curabitur venenatis fringilla lorem. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut gravida ligula a nunc mollis malesuada. Quisque luctus, enim eu finibus suscipit, sem elit faucibus justo, a rhoncus mauris lectus sed ante. Nulla sit amet enim vel risus iaculis scelerisque. Morbi quis mollis nibh, eu bibendum nisi. Vivamus laoreet tincidunt semper. Nulla rutrum vehicula eros, et eleifend nunc fermentum id. Cras et malesuada nibh. Integer condimentum, elit vel varius facilisis, nisl ex vehicula turpis, nec pulvinar ipsum libero vitae dolor. Sed quis turpis eget urna ullamcorper lobortis eu quis ipsum.',
		'Suspendisse in nibh ut metus vestibulum maximus hendrerit in magna. Suspendisse orci quam, placerat id luctus eget, aliquet quis sapien. Nulla sed est neque. Maecenas a leo eu justo vehicula finibus in sed nisl. Curabitur nec lectus tortor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Morbi arcu erat, faucibus non dui a, hendrerit viverra libero. Ut ut imperdiet mauris, quis tincidunt eros. Pellentesque eu mattis quam. Nulla condimentum arcu lorem, eget scelerisque leo condimentum a. Integer dapibus, sem a viverra laoreet, nunc lectus blandit purus, sit amet tempor eros est convallis dolor. Aenean at ligula quis massa vehicula ultrices. Etiam sollicitudin magna et ullamcorper pellentesque. Etiam vestibulum, velit id auctor rutrum, ligula est dapibus enim, non fringilla enim quam at neque. Interdum et malesuada fames ac ante ipsum primis in faucibus.'
	];
	tabs.tabsInitialize(texts, 1);
}());